//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.IssueTransactions = new HashSet<IssueTransaction>();
        }
    
        public short BookID { get; set; }
        public string ISBN { get; set; }
        public string BookTitle { get; set; }
        public short BookCategoryID { get; set; }
        public short AuthorID { get; set; }
        public string Edition { get; set; }
        public short TotalStock { get; set; }
        public short NumberRented { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookCategory BookCategory { get; set; }
        public virtual ICollection<IssueTransaction> IssueTransactions { get; set; }
    }
}
