//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SA40Team07bEntities : DbContext
    {
        public SA40Team07bEntities()
            : base("name=SA40Team07bEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Authors { get; set; }
        public DbSet<BookCategory> BookCategories { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<IssueTransaction> IssueTransactions { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberCategory> MemberCategories { get; set; }
        public DbSet<StaffAccount> StaffAccounts { get; set; }
        public DbSet<vm_returnTran> vm_returnTran { get; set; }
        public DbSet<VM_SearchBook> VM_SearchBook { get; set; }
        public DbSet<VW_Book> VW_Book { get; set; }
        public DbSet<VW_Member> VW_Member { get; set; }
        public DbSet<VW_OutOfStock> VW_OutOfStock { get; set; }
        public DbSet<VW_StaffAccount> VW_StaffAccount { get; set; }
    
        public virtual ObjectResult<BookIssueTran_proc_Result> BookIssueTran_proc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BookIssueTran_proc_Result>("BookIssueTran_proc");
        }
    
        public virtual ObjectResult<BookList_proc_Result> BookList_proc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BookList_proc_Result>("BookList_proc");
        }
    
        public virtual ObjectResult<MemberList_proc_Result> MemberList_proc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MemberList_proc_Result>("MemberList_proc");
        }
    }
}
