//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCategory
    {
        public MemberCategory()
        {
            this.Members = new HashSet<Member>();
        }
    
        public short MCategoryID { get; set; }
        public string MCategoryName { get; set; }
        public short NoOfBooksAllowed { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
