//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.IssueTransactions = new HashSet<IssueTransaction>();
        }
    
        public short MemberID { get; set; }
        public string MemberName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string ContactTitle { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public short MCategoryID { get; set; }
        public Nullable<short> BookBorrowed { get; set; }
        public string MemberStatus { get; set; }
    
        public virtual ICollection<IssueTransaction> IssueTransactions { get; set; }
        public virtual MemberCategory MemberCategory { get; set; }
    }
}
